AWSTemplateFormatVersion: 2010-09-09
Description: "cloudFormation demo"

Parameters:
  Environment:
    Description: Environment Name
    Type: String
  SQSName:
    Description: SQS queue name
    Type: String
  S3Arn:
    Description: S3 bucket for log Arn
    Type: String
  S3Name:
    Description: S3 bucket for log name
    Type: String
    
Resources: 
  lambdaFunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub booksdemo-lambda-policy${Environment}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogsEvents"
                Resource: "*"
        - PolicyName: !Sub booksdemo-lambda-policy-s3${Environment}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: 
                  - s3:GetObjectTagging
                  - s3:GetBucketVersioning
                  - s3:GetLifecycleConfiguration
                  - s3:GetAccessPointPolicyStatus
                  - s3:ReplicateObject
                  - s3:GetBucketPolicyStatus
                  - s3:PutAnalyticsConfiguration
                  - s3:ListBucketMultipartUploads
                  - s3:GetInventoryConfiguration
                  - s3:UpdateJobStatus
                  - s3:GetAnalyticsConfiguration
                  - s3:DeleteMultiRegionAccessPoint
                  - s3:GetStorageLensConfigurationTagging
                  - s3:GetStorageLensConfiguration
                  - s3:GetMultiRegionAccessPointPolicy
                  - s3:GetReplicationConfiguration
                  - s3:GetAccelerateConfiguration
                  - s3:GetBucketRequestPayment
                  - s3:GetIntelligentTieringConfiguration
                  - s3:PutObjectRetention
                  - s3:PutBucketLogging
                  - s3:ListMultipartUploadParts
                  - s3:DescribeMultiRegionAccessPointOperation
                  - s3:InitiateReplication
                  - s3:GetObjectAcl
                  - s3:GetBucketCORS
                  - s3:AbortMultipartUpload
                  - s3:GetObjectVersionForReplication
                  - s3:GetObjectVersionAcl
                  - s3:PutBucketCORS
                  - s3:GetJobTagging
                  - s3:DeleteBucketWebsite
                  - s3:UpdateJobPriority
                  - s3:CreateAccessPointForObjectLambda
                  - s3:GetObject
                  - s3:PutBucketNotification
                  - s3:PutObjectLegalHold
                  - s3:PutBucketVersioning
                  - s3:PutBucketObjectLockConfiguration
                  - s3:GetAccessPointPolicyStatusForObjectLambda
                  - s3:PutBucketRequestPayment
                  - s3:GetBucketOwnershipControls
                Resource: 
                  - !Sub ${S3Arn}
                  - !Sub ${S3Arn}/*
              - Effect: Allow
                Action:
                  - s3:ListJobs
                  - s3:ListAccessPointsForObjectLambda
                  - s3:ListMultiRegionAccessPoints
                  - s3:PutStorageLensConfiguration
                  - s3:ListAccessPoints
                  - s3:CreateJob
                  - s3:ListStorageLensConfigurations
                  - s3:GetAccessPoint
                  - s3:ListAllMyBuckets
                  - s3:GetAccountPublicAccessBlock
                Resource: "*"
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChengeMessageVisibility
                Resource:
                  Fn::Join:
                    - ""
                    -
                      - "arn:aws:sqs:"
                      - Ref: "AWS::Region"
                      - ":"
                      - Ref: "AWS::AccountId"
                      - ":"
                      - !Sub ${SQSName}
                
  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: CloudFormation demo lambda
      FunctionName: !Sub books-demo-log-${Environment}
      Handler: SQSDemo::SQSDemo.Function::FunctionHandler
      MemorySize: 128
      Role: !GetAtt lambdaFunctionIamRole.Arn
      Runtime: dotnetcore3.1
      Timeout: 20
      Environment:
        Variables:
          S3LogBucket: !Sub ${S3Name}
      Code:
        S3Bucket: demo-loudformation-packages 
        S3Key: booksDemoLambda.zip

  EventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn:
        Fn::Join:
          - ""
          -
            - "arn:aws:sqs:"
            - Ref: "AWS::Region"
            - ":"
            - Ref: "AWS::AccountId"
            - ":"
            - !Sub ${SQSName}
      FunctionName: !GetAtt lambdaFunction.Arn
      BatchSize: 10
      Enabled: true
